const kMAX_NODE_NUM_CMDS = 24;
const kMAX_NODE_NAME_SIZE = 20;
const kMAX_CMD_STATUS_SIZE = 24;
const kMAX_ALLOWED_NODES = 120;
const kMAX_ROOM_NODES = (kMAX_ALLOWED_NODES + 2);
const kMAX_ZWAVE_PUSH_EVENTS = (3 * kMAX_ALLOWED_NODES);
const kMAX_ROOM_NAME_SIZE = 24;
const kMAX_SCENE_NAME_SIZE = 24;
const kMAX_SCENE_ACTIONS = 12;
const kTYPE_FLAG_GROUP = 0x77;
const kTYPE_FLAG_ROOM = 0;
const kTYPE_FLAG_HOTKEY = 0x77;
const kTYPE_FLAG_SCENE = 0;

const kTYPE_LOG_EVENTS = 106;
const kTYPE_SYSTEM_LOG_MASK = 108;
const kTYPE_ZWAVE_ADD_NODE = 200;
const kTYPE_ZWAVE_REMOVE_NODE = 201;
const kTYPE_ZWAVE_SEND_DATA = 202;
const kTYPE_ZWAVE_CMD_HANDLER = 203;
const kTYPE_ZWAVE_NODE_NAME = 204;
const kTYPE_ZWAVE_TOTAL_NODES = 205;
const kTYPE_ZWAVE_NODE_INFO = 206;
const kTYPE_ZWAVE_NODE_ALL_INFO = 207;
const kTYPE_ZWAVE_REMOVE_ALL_NODES = 208;
const kTYPE_ZWAVE_NODE_NAME_BY_NODE_ID = 209;
const kTYPE_ZWAVE_REMOVE_NODE_BY_NODE_ID = 210;
const kTYPE_ZWAVE_NODE_INFO_BY_NODE_ID = 211;
const kTYPE_ZWAVE_ROOM_ADD = 212;
const kTYPE_ZWAVE_ROOM_REMOVE = 213;
const kTYPE_ZWAVE_ROOM_ADD_A_NODE = 214;
const kTYPE_ZWAVE_ROOM_REMOVE_A_NODE = 215;
const kTYPE_ZWAVE_ROOM_SET_NAME = 216;
const kTYPE_ZWAVE_ROOM_GET_INFO = 217;
const kTYPE_ZWAVE_ROOM_GET_ALL_INFO = 218;
const kTYPE_ZWAVE_ROOM_TOTAL_ROOMS = 219;
const kTYPE_ZWAVE_ROOM_SET_PARAMETERS = 220;
const kTYPE_ZWAVE_SEND_DATA_MULTI = 221;
const kTYPE_ZWAVE_SCENE_ADD = 222;
const kTYPE_ZWAVE_SCENE_REMOVE = 223;
const kTYPE_ZWAVE_SCENE_SET_NAME = 224;
const kTYPE_ZWAVE_SCENE_SET_PARAMETERS = 225;
const kTYPE_ZWAVE_SCENE_GET_INFO = 226;
const kTYPE_ZWAVE_SCENE_GET_ALL_INFO = 227;
const kTYPE_ZWAVE_SCENE_TOTAL_SCENES = 228;
const kTYPE_ZWAVE_SCENE_DO_ACTION = 229;
const kTYPE_ZWAVE_SCENE_GET_STATUS = 230;
const kTYPE_ZWAVE_SCENE_DISABLE = 231;
const kTYPE_ZWAVE_HISTORY_RECORDS = 232;
const kTYPE_GATEWAY_LIST_ADD_OR_UPDATE = 233;
const kTYPE_GATEWAY_LIST_REMOVE = 234;
const kTYPE_GATEWAY_LIST_ALL = 235;
const kTYPE_ZWAVE_SEND_DATA_MULTI_FAILED_NODES = 236;
const kTYPE_ZWAVE_REPLACE_NODE_BY_NODE_ID = 237;
const kTYPE_ZWAVE_LEARN_MODE = 238;
const kTYPE_ZWAVE_ROOM_DO_ACTION = 239;
const kTYPE_ZWAVE_SECOND_NODE_ALL_INFO = 240;
const kTYPE_ZWAVE_HOUSE_MODE = 241;
const kTYPE_ZWAVE_NODE_MULTI_CHANNEL_NAME = 242;
const kTYPE_ZWAVE_GROUP_ADD = 243;
const kTYPE_ZWAVE_GROUP_GET_ALL_INFO = 244;
const kTYPE_ZWAVE_GROUP_TOTAL_GROUPS = 245;
const kTYPE_ZWAVE_HOTKEY_ADD = 246;
const kTYPE_ZWAVE_HOTKEY_GET_ALL_INFO = 247;
const kTYPE_ZWAVE_HOTKEY_TOTAL_HOTKEYS = 248;
const kTYPE_USER_ACCOUNT_AUTHORITY = 249;
const kTYPE_USER_ACCOUNT_ADD = 250;
const kTYPE_USER_ACCOUNT_REMOVE = 251;
const kTYPE_USER_ACCOUNT_SET_PARAMETERS = 252;
const kTYPE_USER_ACCOUNT_GET_INFO = 253;
const kTYPE_USER_ACCOUNT_GET_ALL_INFO = 254;
const kTYPE_USER_ACCOUNT_TOTAL_ACCOUNTS = 255;
const kTYPE_APP_ANSWER_CALL = 256;
const kTYPE_ZWAVE_AUTOMATIC_BACKUP = 257;
const kTYPE_ZWAVE_DO_BACKUP_NOW = 258;
const kTYPE_ZWAVE_RESTORE_SETTINGS = 259;
const kTYPE_ZWAVE_BACKUP_RESTORE_PERCENT = 260;
const kTYPE_ZWAVE_WAKEUP_INTERVAL = 261;
const kTYPE_ZWAVE_ROOM_THERMO_GET_INFO = 262;
const kTYPE_ZWAVE_ROOM_THERMO_SET_PARAMETERS = 263;
const kTYPE_ZWAVE_NEW_SETPOINT_VALUE = 264;
const kTYPE_SEARCH_EXT_GATEWAY_INFO = 265;
const kTYPE_EXT_GATEWAY_CONNECT = 266;
const kTYPE_EXT_GATEWAY_UPDATE_DEVICES = 267;
const kTYPE_EXT_GATEWAY_REMOVE = 268;
const kTYPE_EXT_GATEWAY_SYNC = 269;
const kTYPE_ZWAVE_START_GET_USER_CODE = 280;
const kTYPE_ZWAVE_GET_USER_CODES = 281;
const kTYPE_ZWAVE_STOP_GET_USER_CODE = 282;
const kTYPE_ZWAVE_ADD_SS_LIST = 283;
const kTYPE_ZWAVE_REMOVE_SS_LIST = 284;
const kTYPE_ZWAVE_GET_SS_LIST = 285;
const kTYPE_ZWAVE_RENAME_SS_LIST = 286;
const kTYPE_ZWAVE_NUM_ENDPOINTS = 287;
const kTYPE_ZWAVE_SAME_SECURITY_LIST = 288;
const kTYPE_ZWAVE_ASSOCIATE_INFO = 289;
const kTYPE_ZWAVE_NODE_SET_ASSOCIATION = 290;
const kTYPE_ZWAVE_OTA_UPGRADE = 291;
const kTYPE_ZWAVE_OTA_PERCENT = 292;
const kTYPE_PRESET_PATROL_CONTROL = 305;
const kTYPE_AWS_CONNECTION_CONTROL = 306;
const kTYPE_DOORBELL_VOLUME = 307;

const kLocalSdkSettingTypeEnum = {
  'TYPE_LOG_EVENTS': kTYPE_LOG_EVENTS,
  'TYPE_SYSTEM_LOG_MASK': kTYPE_SYSTEM_LOG_MASK,
  'TYPE_ZWAVE_ADD_NODE': kTYPE_ZWAVE_ADD_NODE,
  'TYPE_ZWAVE_REMOVE_NODE': kTYPE_ZWAVE_REMOVE_NODE,
  // 'TYPE_ZWAVE_SEND_DATA': kTYPE_ZWAVE_SEND_DATA,
  // 'TYPE_ZWAVE_CMD_HANDLER': kTYPE_ZWAVE_CMD_HANDLER,
  // 'TYPE_ZWAVE_NODE_NAME': kTYPE_ZWAVE_NODE_NAME,
  // 'TYPE_ZWAVE_TOTAL_NODES': kTYPE_ZWAVE_TOTAL_NODES,
  // 'TYPE_ZWAVE_NODE_INFO': kTYPE_ZWAVE_NODE_INFO,
  // 'TYPE_ZWAVE_NODE_ALL_INFO': kTYPE_ZWAVE_NODE_ALL_INFO,
  // 'TYPE_ZWAVE_REMOVE_ALL_NODES': kTYPE_ZWAVE_REMOVE_ALL_NODES,
  // 'TYPE_ZWAVE_NODE_NAME_BY_NODE_ID': kTYPE_ZWAVE_NODE_NAME_BY_NODE_ID,
  // 'TYPE_ZWAVE_REMOVE_NODE_BY_NODE_ID': kTYPE_ZWAVE_REMOVE_NODE_BY_NODE_ID,
  // 'TYPE_ZWAVE_NODE_INFO_BY_NODE_ID': kTYPE_ZWAVE_NODE_INFO_BY_NODE_ID,
  // 'TYPE_ZWAVE_ROOM_ADD': kTYPE_ZWAVE_ROOM_ADD,
  // 'TYPE_ZWAVE_ROOM_REMOVE': kTYPE_ZWAVE_ROOM_REMOVE,
  // 'TYPE_ZWAVE_ROOM_ADD_A_NODE': kTYPE_ZWAVE_ROOM_ADD_A_NODE,
  // 'TYPE_ZWAVE_ROOM_REMOVE_A_NODE': kTYPE_ZWAVE_ROOM_REMOVE_A_NODE,
  // 'TYPE_ZWAVE_ROOM_SET_NAME': kTYPE_ZWAVE_ROOM_SET_NAME,
  // 'TYPE_ZWAVE_ROOM_GET_INFO': kTYPE_ZWAVE_ROOM_GET_INFO,
  // 'TYPE_ZWAVE_ROOM_GET_ALL_INFO': kTYPE_ZWAVE_ROOM_GET_ALL_INFO,
  // 'TYPE_ZWAVE_ROOM_TOTAL_ROOMS': kTYPE_ZWAVE_ROOM_TOTAL_ROOMS,
  // 'TYPE_ZWAVE_ROOM_SET_PARAMETERS': kTYPE_ZWAVE_ROOM_SET_PARAMETERS,
  // 'TYPE_ZWAVE_SEND_DATA_MULTI': kTYPE_ZWAVE_SEND_DATA_MULTI,
  // 'TYPE_ZWAVE_SCENE_ADD': kTYPE_ZWAVE_SCENE_ADD,
  // 'TYPE_ZWAVE_SCENE_REMOVE': kTYPE_ZWAVE_SCENE_REMOVE,
  // 'TYPE_ZWAVE_SCENE_SET_NAME': kTYPE_ZWAVE_SCENE_SET_NAME,
  // 'TYPE_ZWAVE_SCENE_SET_PARAMETERS': kTYPE_ZWAVE_SCENE_SET_PARAMETERS,
  // 'TYPE_ZWAVE_SCENE_GET_INFO': kTYPE_ZWAVE_SCENE_GET_INFO,
  // 'TYPE_ZWAVE_SCENE_GET_ALL_INFO': kTYPE_ZWAVE_SCENE_GET_ALL_INFO,
  // 'TYPE_ZWAVE_SCENE_TOTAL_SCENES': kTYPE_ZWAVE_SCENE_TOTAL_SCENES,
  // 'TYPE_ZWAVE_SCENE_DO_ACTION': kTYPE_ZWAVE_SCENE_DO_ACTION,
  // 'TYPE_ZWAVE_SCENE_GET_STATUS': kTYPE_ZWAVE_SCENE_GET_STATUS,
  // 'TYPE_ZWAVE_SCENE_DISABLE': kTYPE_ZWAVE_SCENE_DISABLE,
  // 'TYPE_ZWAVE_HISTORY_RECORDS': kTYPE_ZWAVE_HISTORY_RECORDS,
  // 'TYPE_GATEWAY_LIST_ADD_OR_UPDATE': kTYPE_GATEWAY_LIST_ADD_OR_UPDATE,
  // 'TYPE_GATEWAY_LIST_REMOVE': kTYPE_GATEWAY_LIST_REMOVE,
  // 'TYPE_GATEWAY_LIST_ALL': kTYPE_GATEWAY_LIST_ALL,
  // 'TYPE_ZWAVE_SEND_DATA_MULTI_FAILED_NODES': kTYPE_ZWAVE_SEND_DATA_MULTI_FAILED_NODES,
  // 'TYPE_ZWAVE_REPLACE_NODE_BY_NODE_ID': kTYPE_ZWAVE_REPLACE_NODE_BY_NODE_ID,
  // 'TYPE_ZWAVE_LEARN_MODE': kTYPE_ZWAVE_LEARN_MODE,
  // 'TYPE_ZWAVE_ROOM_DO_ACTION': kTYPE_ZWAVE_ROOM_DO_ACTION,
  // 'TYPE_ZWAVE_SECOND_NODE_ALL_INFO': kTYPE_ZWAVE_SECOND_NODE_ALL_INFO,
  // 'TYPE_ZWAVE_HOUSE_MODE': kTYPE_ZWAVE_HOUSE_MODE,
  // 'TYPE_ZWAVE_NODE_MULTI_CHANNEL_NAME': kTYPE_ZWAVE_NODE_MULTI_CHANNEL_NAME,
  // 'TYPE_ZWAVE_GROUP_ADD': kTYPE_ZWAVE_GROUP_ADD,
  // 'TYPE_ZWAVE_GROUP_GET_ALL_INFO': kTYPE_ZWAVE_GROUP_GET_ALL_INFO,
  // 'TYPE_ZWAVE_GROUP_TOTAL_GROUPS': kTYPE_ZWAVE_GROUP_TOTAL_GROUPS,
  // 'TYPE_ZWAVE_HOTKEY_ADD': kTYPE_ZWAVE_HOTKEY_ADD,
  // 'TYPE_ZWAVE_HOTKEY_GET_ALL_INFO': kTYPE_ZWAVE_HOTKEY_GET_ALL_INFO,
  // 'TYPE_ZWAVE_HOTKEY_TOTAL_HOTKEYS': kTYPE_ZWAVE_HOTKEY_TOTAL_HOTKEYS,
  // 'TYPE_USER_ACCOUNT_AUTHORITY': kTYPE_USER_ACCOUNT_AUTHORITY,
  // 'TYPE_USER_ACCOUNT_ADD': kTYPE_USER_ACCOUNT_ADD,
  // 'TYPE_USER_ACCOUNT_REMOVE': kTYPE_USER_ACCOUNT_REMOVE,
  // 'TYPE_USER_ACCOUNT_SET_PARAMETERS': kTYPE_USER_ACCOUNT_SET_PARAMETERS,
  // 'TYPE_USER_ACCOUNT_GET_INFO': kTYPE_USER_ACCOUNT_GET_INFO,
  // 'TYPE_USER_ACCOUNT_GET_ALL_INFO': kTYPE_USER_ACCOUNT_GET_ALL_INFO,
  // 'TYPE_USER_ACCOUNT_TOTAL_ACCOUNTS': kTYPE_USER_ACCOUNT_TOTAL_ACCOUNTS,
  // 'TYPE_APP_ANSWER_CALL': kTYPE_APP_ANSWER_CALL,
  // 'TYPE_ZWAVE_AUTOMATIC_BACKUP': kTYPE_ZWAVE_AUTOMATIC_BACKUP,
  // 'TYPE_ZWAVE_DO_BACKUP_NOW': kTYPE_ZWAVE_DO_BACKUP_NOW,
  // 'TYPE_ZWAVE_RESTORE_SETTINGS': kTYPE_ZWAVE_RESTORE_SETTINGS,
  // 'TYPE_ZWAVE_BACKUP_RESTORE_PERCENT': kTYPE_ZWAVE_BACKUP_RESTORE_PERCENT,
  // 'TYPE_ZWAVE_WAKEUP_INTERVAL': kTYPE_ZWAVE_WAKEUP_INTERVAL,
  // 'TYPE_ZWAVE_ROOM_THERMO_GET_INFO': kTYPE_ZWAVE_ROOM_THERMO_GET_INFO,
  // 'TYPE_ZWAVE_ROOM_THERMO_SET_PARAMETERS': kTYPE_ZWAVE_ROOM_THERMO_SET_PARAMETERS,
  // 'TYPE_ZWAVE_NEW_SETPOINT_VALUE': kTYPE_ZWAVE_NEW_SETPOINT_VALUE,
  // 'TYPE_SEARCH_EXT_GATEWAY_INFO': kTYPE_SEARCH_EXT_GATEWAY_INFO,
  // 'TYPE_EXT_GATEWAY_CONNECT': kTYPE_EXT_GATEWAY_CONNECT,
  // 'TYPE_EXT_GATEWAY_UPDATE_DEVICES': kTYPE_EXT_GATEWAY_UPDATE_DEVICES,
  // 'TYPE_EXT_GATEWAY_REMOVE': kTYPE_EXT_GATEWAY_REMOVE,
  // 'TYPE_EXT_GATEWAY_SYNC': kTYPE_EXT_GATEWAY_SYNC,
  // 'TYPE_ZWAVE_START_GET_USER_CODE': kTYPE_ZWAVE_START_GET_USER_CODE,
  // 'TYPE_ZWAVE_GET_USER_CODES': kTYPE_ZWAVE_GET_USER_CODES,
  // 'TYPE_ZWAVE_STOP_GET_USER_CODE': kTYPE_ZWAVE_STOP_GET_USER_CODE,
  // 'TYPE_ZWAVE_ADD_SS_LIST': kTYPE_ZWAVE_ADD_SS_LIST,
  // 'TYPE_ZWAVE_REMOVE_SS_LIST': kTYPE_ZWAVE_REMOVE_SS_LIST,
  // 'TYPE_ZWAVE_GET_SS_LIST': kTYPE_ZWAVE_GET_SS_LIST,
  // 'TYPE_ZWAVE_RENAME_SS_LIST': kTYPE_ZWAVE_RENAME_SS_LIST,
  // 'TYPE_ZWAVE_NUM_ENDPOINTS': kTYPE_ZWAVE_NUM_ENDPOINTS,
  // 'TYPE_ZWAVE_SAME_SECURITY_LIST': kTYPE_ZWAVE_SAME_SECURITY_LIST,
  // 'TYPE_ZWAVE_ASSOCIATE_INFO': kTYPE_ZWAVE_ASSOCIATE_INFO,
  // 'TYPE_ZWAVE_NODE_SET_ASSOCIATION': kTYPE_ZWAVE_NODE_SET_ASSOCIATION,
  // 'TYPE_ZWAVE_OTA_UPGRADE': kTYPE_ZWAVE_OTA_UPGRADE,
  // 'TYPE_ZWAVE_OTA_PERCENT': kTYPE_ZWAVE_OTA_PERCENT,
  // 'TYPE_PRESET_PATROL_CONTROL': kTYPE_PRESET_PATROL_CONTROL,
  // 'TYPE_AWS_CONNECTION_CONTROL': kTYPE_AWS_CONNECTION_CONTROL,
  // 'TYPE_DOORBELL_VOLUME': kTYPE_DOORBELL_VOLUME,
};